package com.mxraven.admin.model;

/**
 * Effective tenant quota values after merging the guardrail profile with any
 * tenant overrides, plus the profile they were derived from.
 */
public record EffectiveTenantQuotas(
        String profileId,
        String profileRef,
        String profileDisplayName,
        boolean profileIsActive,
        Integer maxSubmissionListeners,
        Integer maxMtaListeners,
        Integer maxDomains,
        Integer maxInboundRoutes,
        Integer maxApiKeys,
        Integer maxApiKeysPerListener,
        Integer maxRoutingRules,
        Integer maxRoutingRulesPerListener,
        Integer maxSmtpRelays,
        Integer maxStorageIntegrations,
        Integer maxWebhookEndpoints,
        Integer maxAutoReplyTemplates,
        Integer maxIdentityProviders,
        Integer maxManualTenantSuppressions,
        Integer maxRecipientSets,
        Integer maxRecipientSetMembers,
        Integer maxRecipientSetMembersPerSet,
        Integer maxDedicatedIpLeases,
        Integer maxDedicatedIpAddresses,
        Double submissionBaseRecipientRatePerMinute,
        Integer submissionBurst,
        Integer submissionMaxConcurrency,
        Double submissionMinRateMultiplier,
        Double mtaMessageRatePerMinute,
        Double mtaRecipientRatePerMinute,
        Double mtaTaskRatePerMinute,
        Integer mtaBurst,
        Integer mtaMaxConcurrency,
        Boolean mtaRspamdScanningEnabled,
        Integer reputationRecoveryTargetScore,
        Integer reputationSpamComplaintWeight,
        Integer reputationPolicyViolationWeight,
        Integer reputationHardBounceWeight,
        Integer reputationUnsubscribeWeight,
        Integer reputationNegativeStreakBonusCap,
        Long reputationUnsubscribeWindowSeconds,
        Long reputationUnsubscribeThreshold,
        Long reputationRecoveryQuietPeriodSeconds,
        Long reputationRecoverySuccessesPerPoint,
        Boolean abuseControlEnabled,
        Boolean abuseAutoPauseEnabled,
        Long abuseEvaluationWindowSeconds,
        Long abuseMinEgressTasks,
        Double abuseSuppressedSendRateThreshold,
        Double abuseSuppressionAppliedRateThreshold,
        Double abuseSpamComplaintRateThreshold,
        Double abuseHardBounceRateThreshold,
        Double abusePolicyViolationRateThreshold,
        Double abuseUnsubscribeRateThreshold,
        Integer abuseLowReputationScoreThreshold) {
}
